export const questions = [
  {
    id: 1,
    question: "What subjects/topics do you need to study? (comma separated)",
    key: "subjects",
    type: "text",
    placeholder: "e.g., Mathematics, Biology, History",
    required: true,
    category: "basic",
  },
  {
    id: 2,
    question: "How many hours can you study daily?",
    key: "hoursPerDay",
    type: "number",
    placeholder: "2",
    min: 1,
    max: 16,
    required: true,
    category: "basic",
  },
  {
    id: 3,
    question: "What's your weakest subject?",
    key: "weakestSubject",
    type: "text",
    placeholder: "Physics",
    required: true,
    category: "basic",
  },
  {
    id: 4,
    question: "When is your target completion date?",
    key: "targetDate",
    type: "date",
    placeholder: "",
    min: new Date().toISOString().split("T")[0],
    required: true,
    category: "basic",
  },
  {
    id: 5,
    question: "What are your preferred learning style(s)?",
    key: "learningStyles",
    type: "multi-select",
    options: ["Visual", "Auditory", "Kinesthetic", "Reading/Writing"],
    placeholder: "Select all that apply",
    required: true,
    category: "preferences",
  },
  {
    id: 6,
    question: "What study resources do you have available?",
    key: "existingResources",
    type: "multi-select",
    options: [
      "Textbooks",
      "Online Courses",
      "Tutor",
      "Study Group",
      "Practice Exams",
      "Educational Apps",
      "YouTube Tutorials",
      "Flashcards",
      "Notes",
      "Audio Lectures",
    ],
    placeholder: "Select available resources",
    required: true,
    category: "resources",
  },
  {
    id: 7,
    question: "When do you prefer to study?",
    key: "studyTimes",
    type: "multi-select",
    options: [
      "Morning (6AM-12PM)",
      "Afternoon (12PM-5PM)",
      "Evening (5PM-9PM)",
      "Night (9PM-12AM)",
    ],
    placeholder: "Select preferred times",
    required: true,
    category: "preferences",
  },
  {
    id: 8,
    question: "What is your main study goal?",
    key: "studyGoal",
    type: "select",
    options: [
      "Exam Preparation",
      "Skill Development",
      "Course Completion",
      "General Knowledge",
      "Competition Preparation",
      "Certification",
      "Self-Improvement",
    ],
    placeholder: "Select main goal",
    required: true,
    category: "basic",
  },
  // New questions start here
  {
    id: 9,
    question: "Rate your energy level during different times of the day",
    key: "energyLevels",
    type: "slider-group",
    options: ["Morning", "Afternoon", "Evening", "Night"],
    min: 1,
    max: 5,
    labels: ["Very Low", "Very High"],
    required: false,
    category: "preferences",
  },
  {
    id: 10,
    question: "Rate your current proficiency in each subject (1-5)",
    key: "subjectProficiency",
    type: "dynamic-slider-group",
    dynamicOptions: "subjects",
    min: 1,
    max: 5,
    labels: ["Beginner", "Advanced"],
    required: false,
    category: "assessment",
  },
  {
    id: 11,
    question: "Do you have any recurring commitments during the week?",
    key: "commitments",
    type: "schedule-grid",
    rowOptions: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    columnOptions: ["Morning", "Afternoon", "Evening", "Night"],
    placeholder: "Select unavailable times",
    required: false,
    category: "schedule",
  },
  {
    id: 12,
    question: "How long can you focus before needing a break?",
    key: "focusDuration",
    type: "select",
    options: [
      "15-20 minutes",
      "25-30 minutes",
      "45-60 minutes",
      "More than 60 minutes",
    ],
    placeholder: "Select focus duration",
    required: false,
    category: "habits",
  },
  {
    id: 13,
    question: "What distracts you most while studying?",
    key: "distractions",
    type: "multi-select",
    options: [
      "Social Media",
      "Phone Calls/Messages",
      "Noise",
      "Family/Roommates",
      "Hunger/Snacking",
      "Internet Browsing",
      "Thoughts/Daydreaming",
      "Fatigue",
    ],
    placeholder: "Select common distractions",
    required: false,
    category: "habits",
  },
  {
    id: 14,
    question: "How do you prefer to track your progress?",
    key: "progressTracking",
    type: "multi-select",
    options: [
      "Daily Checkpoints",
      "Weekly Goals",
      "Practice Tests",
      "Self-Assessment Quizzes",
      "Teaching Concepts to Others",
      "Flashcard Mastery",
      "Project Completion",
    ],
    placeholder: "Select tracking methods",
    required: false,
    category: "preferences",
  },
  {
    id: 15,
    question: "What motivates you to study?",
    key: "motivations",
    type: "multi-select",
    options: [
      "Career Goals",
      "Knowledge Mastery",
      "Grades/Scores",
      "Competition",
      "Personal Growth",
      "Rewards/Treats",
      "Accountability to Others",
      "Interest in Subject",
    ],
    placeholder: "Select motivational factors",
    required: false,
    category: "habits",
  },
  {
    id: 16,
    question: "Rate the difficulty of each subject for you (1-5)",
    key: "subjectDifficulty",
    type: "dynamic-slider-group",
    dynamicOptions: "subjects",
    min: 1,
    max: 5,
    labels: ["Easy", "Very Difficult"],
    required: false,
    category: "assessment",
  },
  {
    id: 17,
    question: "Do you have any specific learning challenges?",
    key: "learningChallenges",
    type: "multi-select",
    options: [
      "Difficulty Concentrating",
      "Procrastination",
      "Test Anxiety",
      "Reading Comprehension",
      "Note-Taking",
      "Memory Recall",
      "Math Anxiety",
      "Information Overload",
      "None",
    ],
    placeholder: "Select challenges if any",
    required: false,
    category: "assessment",
  },
  {
    id: 18,
    question: "How do you prefer to review material?",
    key: "reviewMethods",
    type: "multi-select",
    options: [
      "Re-reading Notes",
      "Practice Problems",
      "Creating Summaries",
      "Teaching Others",
      "Flashcards",
      "Mind Maps",
      "Group Discussion",
      "Self-Testing",
    ],
    placeholder: "Select review methods",
    required: false,
    category: "preferences",
  },
  {
    id: 19,
    question: "What rewards motivate you to complete study sessions?",
    key: "rewards",
    type: "multi-select",
    options: [
      "Short Breaks",
      "Social Media Time",
      "Snacks/Treats",
      "Physical Activity",
      "TV/Movies",
      "Gaming",
      "Social Activities",
      "None - Satisfaction of Progress",
    ],
    placeholder: "Select rewards",
    required: false,
    category: "habits",
  },
  {
    id: 20,
    question: "What is your study environment preference?",
    key: "environment",
    type: "multi-select",
    options: [
      "Silent Space",
      "Background Music",
      "Coffee Shop/Public",
      "Library",
      "Outdoors",
      "Home Desk",
      "Group Setting",
      "Virtual/Online",
    ],
    placeholder: "Select environment preferences",
    required: false,
    category: "preferences",
  },
];
